name: chess_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.1.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sketchess_logo.png
    - assets/sketchess_logo_login.png
    - assets/login_icon.png
    - assets/registration_icon.png
    - assets/info_icon.png
